apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdfding.fullname" . }}
  labels:
    {{- include "pdfding.labels" . | nindent 4 }}
data:
  HOST_NAME: {{ .Values.pdfding.config.hostName | quote }}
  HOST_PORT: {{ .Values.pdfding.config.hostPort | quote }}
  DEFAULT_THEME: {{ .Values.pdfding.config.defaultTheme | quote }}
  DEFAULT_THEME_COLOR: {{ .Values.pdfding.config.defaultThemeColor | quote }}
  {{- if not .Values.pdfding.config.accountEmailVerification.enabled }}
  ACCOUNT_EMAIL_VERIFICATION: "FALSE"
  {{- end }}
  {{- if .Values.pdfding.config.disableUserSignup.enabled }}
  DISABLE_USER_SIGNUP: "TRUE"
  {{- end }}
  {{- if not ( eq .Values.pdfding.config.logLevel "ERROR" ) }}
  LOG_LEVEL: {{ .Values.pdfding.config.logLevel | quote }}
  {{- end }}
  {{- if not .Values.pdfding.existingSecret }}
  SECRET_KEY: {{ .Values.pdfding.config.secretKey | quote }}
  {{- end }}
  {{- if not .Values.pdfding.config.csrfCookieSecure.enabled }}
  CSRF_COOKIE_SECURE: "FALSE"
  {{- end }}
  {{- if not .Values.pdfding.config.sessionCookieSecure.enabled }}
  SESSION_COOKIE_SECURE: "FALSE"
  {{- end }}
  {{- if .Values.pdfding.config.secureSslRedirect.enabled }}
  SECURE_SSL_REDIRECT: "TRUE"
  {{- end }}
  {{- if .Values.pdfding.config.secureHstsSeconds }}
  SECURE_HSTS_SECONDS: {{ .Values.pdfding.config.secureHstsSeconds | quote }}
  {{- end }}
  {{- if not ( eq .Values.pdfding.config.accountDefaultHttpProtocol "https" ) }}
  ACCOUNT_DEFAULT_HTTP_PROTOCOL: {{ .Values.pdfding.config.accountDefaultHttpProtocol | quote }}
  {{- end }}
  {{- if eq .Values.pdfding.config.database.type "POSTGRES" }}
  DATABASE_TYPE: {{ .Values.pdfding.config.database.type | quote }}
  POSTGRES_HOST: {{ .Values.pdfding.config.database.postgresHost | quote }}
  POSTGRES_NAME: {{ .Values.pdfding.config.database.postgresName | quote }}
  POSTGRES_USER: {{ .Values.pdfding.config.database.postgresUser | quote }}
  {{- if not .Values.pdfding.existingSecret }}
  POSTGRES_PASSWORD: {{ .Values.pdfding.config.database.postgresPassword | quote }}
  {{- end }}
  POSTGRES_PORT: {{ .Values.pdfding.config.database.postgresPort | quote }}
  {{- end }}
  {{- if .Values.pdfding.config.oidc.enabled }}
  OIDC_ENABLE: "TRUE"
  OIDC_CLIENT_ID: {{ .Values.pdfding.config.oidc.clientId | quote }}
  {{- if not .Values.pdfding.existingSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.pdfding.config.oidc.clientSecret | quote }}
  {{- end }}
  OIDC_AUTH_URL: {{ .Values.pdfding.config.oidc.authUrl | quote }}
  {{- if .Values.pdfding.config.oidc.oidc_only.enabled }}
  OIDC_ONLY: "TRUE"
  {{- end }}
  OIDC_PROVIDER_NAME: {{ .Values.pdfding.config.oidc.providerName | quote }}
  {{- end }}
  {{- if eq .Values.pdfding.config.email.backend "SMTP" }}
  SMTP_HOST: {{ .Values.pdfding.config.email.smtpHost | quote }}
  SMTP_PORT: {{ .Values.pdfding.config.email.smtpPort | quote }}
  SMTP_USER: {{ .Values.pdfding.config.email.smtpUser | quote }}
  {{- if not .Values.pdfding.existingSecret }}
  SMTP_PASSWORD: {{ .Values.pdfding.config.email.smtpPassword | quote }}
  {{- end }}
  {{- if .Values.pdfding.config.email.smtpUseTls.enabled }}
  SMTP_USE_TLS: "TRUE"
  {{- end }}
  {{- if .Values.pdfding.config.email.smtpUseSsl.enabled }}
  SMTP_USE_SSL: "TRUE"
  {{- end }}
  {{- end }}
  {{- if .Values.pdfding.config.consumption.enabled }}
  CONSUME_ENABLE: "TRUE"
  {{- if not .Values.pdfding.config.consumption.skipExisting.enabled }}
  CONSUME_SKIP_EXISTING: "FALSE"
  {{- end }}
  CONSUME_TAGS: {{ .Values.pdfding.config.consumption.tags | quote }}
  {{- end }}
  {{- if .Values.pdfding.config.backup.enabled }}
  BACKUP_ENABLE: "TRUE"
  BACKUP_ENDPOINT: {{ .Values.pdfding.config.backup.endpoint | quote }}
  BACKUP_ACCESS_KEY: {{ .Values.pdfding.config.backup.accessKey | quote }}
  {{- if not .Values.pdfding.existingSecret }}
  BACKUP_SECRET_KEY: {{ .Values.pdfding.config.backup.secretKey | quote }}
  {{- end }}
  BACKUP_BUCKET_NAME: {{ .Values.pdfding.config.backup.bucketName | quote }}
  BACKUP_SCHEDULE: {{ .Values.pdfding.config.backup.schedule | quote }}
  {{- if .Values.pdfding.config.backup.tls.enabled }}
  BACKUP_SECURE: "TRUE"
  {{- end }}
  {{- if .Values.pdfding.config.backup.encryption.enabled }}
  BACKUP_ENCRYPTION_ENABLE: "TRUE"
  BACKUP_ENCRYPTION_SALT: {{ .Values.pdfding.config.backup.encryption.salt | quote }}
  {{- if not .Values.pdfding.existingSecret }}
  BACKUP_ENCRYPTION_PASSWORD: {{ .Values.pdfding.config.backup.encryption.password | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- range $key, $value := .Values.pdfding.extraConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
