{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pdfding.fullname" . }}
  labels:
    {{- include "pdfding.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.enabled }}
  tls:
    - hosts:
        - {{ .Values.pdfding.config.hostName | quote }}
      secretName: pdfding-tls
  {{- end }}
  rules:
    - host: {{ .Values.pdfding.config.hostName | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "pdfding.fullname" . }}
                port:
                  number: {{ .Values.pdfding.config.hostPort }}
{{- end }}
