{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pdfding.fullname" . }}-media
  labels:
    {{- include "pdfding.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.mediaSize | quote }}
{{- if .Values.persistence.storageClassName }}
{{- if (eq "-" .Values.persistence.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
{{- end }}
{{- end }}
{{- if not ( eq .Values.pdfding.config.database.type "POSTGRES" ) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pdfding.fullname" . }}-db
  labels:
    {{- include "pdfding.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dbSize | quote }}
{{- if .Values.persistence.storageClassName }}
{{- if (eq "-" .Values.persistence.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
