apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdfding.fullname" . }}
  labels:
    {{- include "pdfding.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.pdfding.config.hostPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pdfding.selectorLabels" . | nindent 4 }}
