# This file contains the values used for deploying PdfDing's demo instance via helm

pdfding:
  config:
    hostName: "demo.pdfding.com"
    disableUserSignup:
      enabled: true
    secureHstsSeconds: "31536000"

  extraConfig:
    # Do not use this setting in your installation! This will delete the sqlite database when the container starts!
    DEMO_MODE: "TRUE"

  existingSecret: "pdfding"

serviceAccount:
  create: true

replicas: 1

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

# resetting data every 60 seconds is achieved by using the liveness probe
livenessProbe:
  failureThreshold: 1
  initialDelaySeconds: 60
  periodSeconds: 60

# because demo data needs to be created so we use a high failureThreshold
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 2
  failureThreshold: 60

podSecurityContext:
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls:
    enabled: true
