## PdfDing Helm Chart for Kubernetes
## Maintainer: mrmn2

## Provide a name in place of `pdfding`
nameOverride: ""
## String to fully override `"pdfding.fullname"`
fullnameOverride: ""

## PdfDing configuration
## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md
pdfding:
  config:
    ## General configuration settings
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md#general

    # -- The host/domain names where PdfDing will be reachable.
    # -- NOTE: Only a single host name can be provided!
    hostName: "pdfding.com"
    # -- Allows to set a custom port for the PdfDing server.
    hostPort: "8000"
    # -- Specify the default theme. Possible values are: `light`, `dark`, `creme`
    defaultTheme: "dark"
    # -- Specify the default theme color. Possible values are: `green`, `blue`, `gray`, `red`, `pink`, `orange`, `brown`
    defaultThemeColor: "green"
    # -- Set the log level. Possible values are: `DEBUG`, `INFO`, `WARNING`, `ERROR`
    logLevel: "ERROR"
    # -- Block users until they have verified their email address.
    accountEmailVerification:
      enabled: true
    # -- Flag for disabling user signup.
    disableUserSignup:
      enabled: false

    ## Security related configuration settings
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md#security-related

    # -- This value is the key to securing signed data. Should be to a large random value!
    # -- Note: secretKey will be overridden if existingSecret is set!
    secretKey: "some_secret"
    # -- Enable to avoid transmitting the CSRF cookie over HTTP accidentally.
    csrfCookieSecure:
      enabled: true
    # -- Enable to avoid transmitting the session cookie over HTTP accidentally.
    sessionCookieSecure:
      enabled: true
    # -- Enable redirects all non-HTTPS requests to HTTPS.
    # -- If PdfDing is running behind a reverse proxy this can cause infinite redirects.
    secureSslRedirect:
      enabled: false
    # -- For sites that should only be accessed over HTTPS, you can instruct modern browsers to refuse to connect
    # -- to your domain name via an insecure connection (for a given period of time) by setting the
    # -- “Strict-Transport-Security” header. `secureHstsSeconds` will set this header for you on all HTTPS responses
    # -- for the specified number of seconds. Test this with a small value first. If everything works it can be set
    # -- to a large value, e.g. `31536000` (1 year) , in order to protect infrequent visitors.
    secureHstsSeconds: ""
    # -- The default protocol for account related URLs, e.g. for the password forgotten procedure.
    # -- Possible values are: `https`, `http`
    accountDefaultHttpProtocol: "https"

    ## Database related settings
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md#databases
    database:
      # -- Specify which database type should be used. Possible values are: `SQLITE`, `POSTGRES`
      type: "SQLITE"
      # type: "POSTGRES"
      ## -- The host of the postgres DB
      # postgresHost: "postgres.pdfding.com"
      ## -- The name of the postgres DB
      # postgresName: "pdfding"
      ## -- The name of the postgres user
      # postgresUser: "pdfding"
      ## -- The password for the postgres DB
      ## -- Note: postgresPassword will be overridden if existingSecret is set!
      # postgresPassword: "some_password"
      ## -- The port of the postgres DB.
      # postgresPort: "5432"

    ## OIDC related configuration settings
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md#sso-via-oidc
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/guides.md#sso-via-oidc
    oidc:
      # -- enables OIDC
      enabled: false
      ## -- PdfDing's OIDC client id.
      # clientId: "pdfding"
      ## -- PdfDing's OIDC client secret. Should be a large random value!
      ## -- Note: clientSecret will be overridden if existingSecret is set!
      # clientSecret: "some_secret"
      ## -- The URL to the OpenID configuration of the auth server.
      # authUrl: "https://auth.pdfding.com/.well-known/openid-configuration"
      ## -- Enable OIDC only authentication
      # oidc_only:
      #   enabled: true
      ## -- The name of the OIDC provider. The name will be displayed on the login screen as
      ## -- `OIDC_LOG IN VIA <PROVIDER_NAME>`.
      # providerName: "Authelia"

    ## Email related settings
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md#emails
    email:
      # -- Whether to send account related emails, e.g a password reset or account verification, to the console
      # -- or via an SMTP server.
      backend: "CONSOLE"
      # backend: "SMTP"
      ## -- The host/domain name of the SMTP server.
      # smtpHost: "pdfding.com"
      ## -- The port of the SMTP server.
      # smtpPort: "587"
      ## -- The username used for logging into the SMTP server.
      # smtpUser: "pdfding"
      ## -- The password used for logging into the SMTP server.
      ## -- Note: smtpPassword will be overridden if existingSecret is set!
      # smtpPassword: "some_password"
      ## -- Note that `smtpUseTls`/`smtpUseSsl` are mutually exclusive.
      ## -- Enable securing the connection to the SMTP server with TLS.
      # smtpUseTls:
      #   enabled: false
      ## -- Enable securing the connection to the SMTP server with SSL.
      # smtpUseSsl:
      #   enabled: false

    ## Consumption directory configuration settings
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md#consumption-directory
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/guides.md#consumption-directory
    ## Note that the consumption directory an cause problems with replicas > 1!
    consumption:
      # -- enable the consumption folder as an alternative way for adding PDFs.
      enabled: false
      ## -- Enable skipping the addition of PDF files if the user already has PDF with the same name and file size.
      ## skipExisting:
      ##   enabled: true
      ## -- The tags that should be added to PDFs created via the consumption folder.
      ## -- The tags should be separated via a comma.
      ## tags: "consumed"

    ## Backup configuration settings
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md#consumption-directory
    ## Ref: https://github.com/mrmn2/PdfDing/blob/master/docs/guides.md#backups
    ## Note that the backup of Postgres databases is as of now not supported.
    ## Postgres databases should be backed up by using pg_dump.
    ## Note that automated backups can cause problems with replicas > 1!
    backup:
      # -- Enable automated backups to S3 compatible storage.
      # -- Note:
      # -- Note: secretKey, encryption.password will be overridden if existingSecret is set!
      enabled: false
      ## -- The endpoint of the S3 compatible storage.
      # endpoint: "s3.pdfding.com"
      ## -- The access key of the S3 compatible storage.
      # accessKey: "some_access_key"
      ## -- The secret key of the S3 compatible storage.
      # secretKey: "some_secret_key"
      ## -- The name of the bucket where PdfDing should be backed up to.
      # bucketName: "some_bucket"
      ## -- The schedule for the periodic backups. Example: `0 2 * * *`. This schedule will start the backup
      ## -- every night at 2:00. More information can be found here: https://crontab.guru/#0_2_*_*_*.
      # schedule: "0 2 * * *"
      ## -- Enable using a secure (TLS) connection to the S3 service
      # tls:
      #   enabled: false
      ## -- Enable encrypted backups.
      ## -- IMPORTANT: If you enable encrypted backups or change the encryption password/salt, it is absolutely
      ## -- necessary to delete your existing backups in the S3 compatible storage. Not doing so will destroy your
      ## -- backup!
      # encryption:
      ## -- Enable encrypted backups
      #   enabled: false
      ## -- Password used for generating the encryption key. The encryption key generation is done via PBKDF2
      ## -- with 1000000 iterations. Should be to a large random value!
      #   password: "some_password"
      ## -- Encryption salt
      #   salt: "some_salt"

  ## Specify further environment variables that should be added to the pod
  extraConfig: []
    # EXTRA_KEY: EXTRA_VALUE

  ## Existing Kubernetes Secret that contains PdfDing's secrets,
  ## e.g. SECRET_KEY, OIDC_CLIENT_SECRET, POSTGRES_PASSWORD
  existingSecret: ""
  # existingSecret: "pdfding"


## ServiceAccount configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Number of PdfDing pods
replicas: 1

### Enabling this will persist the database and media directories
persistence:
  enabled: false
  storageClassName: ""
  # -- size of the sqlite pv
  dbSize: 500Mi
  # -- size of the media pv
  mediaSize: 10Gi

## Secrets with credentials to pull images from a private registry
imagePullSecrets: []

## PdfDing image
image:
  repository: mrmn/pdfding
  pullPolicy: IfNotPresent
## Overrides the image tag whose default is the chart appVersion.
#  tag: 1.5.7

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
#  limits:
#    cpu: 500m
#    memory: 512Mi
#  requests:
#    cpu: 250m
#    memory: 256Mi

## Configure liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1

## Extra annotations for pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

## Extra labels for pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext: {}
  # fsGroup: 1000
  # runAsGroup: 1000
  # runAsNonRoot: true
  # runAsUser: 1000

## Configure Container Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
containerSecurityContext: {}
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## PdfDing service parameters
service:
  type: ClusterIP
  annotations: {}
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

## PdfDing ingress parameters
ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt
  path: /
  pathType: Prefix
  tls:
    enabled: false

## Node labels selector for pods assignment
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}

## Tolerations for pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Affinity for pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
